# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x65vents.proto\"H\n\x0fTelegramContext\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\r\x12\x12\n\nmessage_id\x18\x02 \x01(\r\x12\x10\n\x08username\x18\x03 \x01(\t\"\x10\n\x0eTwitterContext\"\x89\x01\n\x11HashSearchRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\thash_type\x18\x02 \x01(\x05\x12$\n\x08telegram\x18\x03 \x01(\x0b\x32\x10.TelegramContextH\x00\x12\"\n\x07twitter\x18\x04 \x01(\x0b\x32\x0f.TwitterContextH\x00\x42\t\n\x07\x63ontext\"t\n\x10URLSearchRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12$\n\x08telegram\x18\x03 \x01(\x0b\x32\x10.TelegramContextH\x00\x12\"\n\x07twitter\x18\x04 \x01(\x0b\x32\x0f.TwitterContextH\x00\x42\t\n\x07\x63ontext\"\x86\x01\n\x0bScanRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x15\n\rartifact_type\x18\x02 \x01(\t\x12$\n\x08telegram\x18\x03 \x01(\x0b\x32\x10.TelegramContextH\x00\x12\"\n\x07twitter\x18\x04 \x01(\x0b\x32\x0f.TwitterContextH\x00\x42\t\n\x07\x63ontextb\x06proto3'
)




_TELEGRAMCONTEXT = _descriptor.Descriptor(
  name='TelegramContext',
  full_name='TelegramContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_id', full_name='TelegramContext.chat_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='TelegramContext.message_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='TelegramContext.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=88,
)


_TWITTERCONTEXT = _descriptor.Descriptor(
  name='TwitterContext',
  full_name='TwitterContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=106,
)


_HASHSEARCHREQUEST = _descriptor.Descriptor(
  name='HashSearchRequest',
  full_name='HashSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='HashSearchRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_type', full_name='HashSearchRequest.hash_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telegram', full_name='HashSearchRequest.telegram', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twitter', full_name='HashSearchRequest.twitter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context', full_name='HashSearchRequest.context',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=109,
  serialized_end=246,
)


_URLSEARCHREQUEST = _descriptor.Descriptor(
  name='URLSearchRequest',
  full_name='URLSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='URLSearchRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telegram', full_name='URLSearchRequest.telegram', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twitter', full_name='URLSearchRequest.twitter', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context', full_name='URLSearchRequest.context',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=248,
  serialized_end=364,
)


_SCANREQUEST = _descriptor.Descriptor(
  name='ScanRequest',
  full_name='ScanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='ScanRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artifact_type', full_name='ScanRequest.artifact_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telegram', full_name='ScanRequest.telegram', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twitter', full_name='ScanRequest.twitter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context', full_name='ScanRequest.context',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=367,
  serialized_end=501,
)

_HASHSEARCHREQUEST.fields_by_name['telegram'].message_type = _TELEGRAMCONTEXT
_HASHSEARCHREQUEST.fields_by_name['twitter'].message_type = _TWITTERCONTEXT
_HASHSEARCHREQUEST.oneofs_by_name['context'].fields.append(
  _HASHSEARCHREQUEST.fields_by_name['telegram'])
_HASHSEARCHREQUEST.fields_by_name['telegram'].containing_oneof = _HASHSEARCHREQUEST.oneofs_by_name['context']
_HASHSEARCHREQUEST.oneofs_by_name['context'].fields.append(
  _HASHSEARCHREQUEST.fields_by_name['twitter'])
_HASHSEARCHREQUEST.fields_by_name['twitter'].containing_oneof = _HASHSEARCHREQUEST.oneofs_by_name['context']
_URLSEARCHREQUEST.fields_by_name['telegram'].message_type = _TELEGRAMCONTEXT
_URLSEARCHREQUEST.fields_by_name['twitter'].message_type = _TWITTERCONTEXT
_URLSEARCHREQUEST.oneofs_by_name['context'].fields.append(
  _URLSEARCHREQUEST.fields_by_name['telegram'])
_URLSEARCHREQUEST.fields_by_name['telegram'].containing_oneof = _URLSEARCHREQUEST.oneofs_by_name['context']
_URLSEARCHREQUEST.oneofs_by_name['context'].fields.append(
  _URLSEARCHREQUEST.fields_by_name['twitter'])
_URLSEARCHREQUEST.fields_by_name['twitter'].containing_oneof = _URLSEARCHREQUEST.oneofs_by_name['context']
_SCANREQUEST.fields_by_name['telegram'].message_type = _TELEGRAMCONTEXT
_SCANREQUEST.fields_by_name['twitter'].message_type = _TWITTERCONTEXT
_SCANREQUEST.oneofs_by_name['context'].fields.append(
  _SCANREQUEST.fields_by_name['telegram'])
_SCANREQUEST.fields_by_name['telegram'].containing_oneof = _SCANREQUEST.oneofs_by_name['context']
_SCANREQUEST.oneofs_by_name['context'].fields.append(
  _SCANREQUEST.fields_by_name['twitter'])
_SCANREQUEST.fields_by_name['twitter'].containing_oneof = _SCANREQUEST.oneofs_by_name['context']
DESCRIPTOR.message_types_by_name['TelegramContext'] = _TELEGRAMCONTEXT
DESCRIPTOR.message_types_by_name['TwitterContext'] = _TWITTERCONTEXT
DESCRIPTOR.message_types_by_name['HashSearchRequest'] = _HASHSEARCHREQUEST
DESCRIPTOR.message_types_by_name['URLSearchRequest'] = _URLSEARCHREQUEST
DESCRIPTOR.message_types_by_name['ScanRequest'] = _SCANREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelegramContext = _reflection.GeneratedProtocolMessageType('TelegramContext', (_message.Message,), {
  'DESCRIPTOR' : _TELEGRAMCONTEXT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:TelegramContext)
  })
_sym_db.RegisterMessage(TelegramContext)

TwitterContext = _reflection.GeneratedProtocolMessageType('TwitterContext', (_message.Message,), {
  'DESCRIPTOR' : _TWITTERCONTEXT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:TwitterContext)
  })
_sym_db.RegisterMessage(TwitterContext)

HashSearchRequest = _reflection.GeneratedProtocolMessageType('HashSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _HASHSEARCHREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:HashSearchRequest)
  })
_sym_db.RegisterMessage(HashSearchRequest)

URLSearchRequest = _reflection.GeneratedProtocolMessageType('URLSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _URLSEARCHREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:URLSearchRequest)
  })
_sym_db.RegisterMessage(URLSearchRequest)

ScanRequest = _reflection.GeneratedProtocolMessageType('ScanRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCANREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:ScanRequest)
  })
_sym_db.RegisterMessage(ScanRequest)


# @@protoc_insertion_point(module_scope)
