# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x65vents.proto\"H\n\x0fTelegramContext\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\r\x12\x12\n\nmessage_id\x18\x02 \x01(\r\x12\x10\n\x08username\x18\x03 \x01(\t\"\x10\n\x0eTwitterContext\"^\n\x07\x43ontext\x12$\n\x08telegram\x18\x01 \x01(\x0b\x32\x10.TelegramContextH\x00\x12\"\n\x07twitter\x18\x02 \x01(\x0b\x32\x0f.TwitterContextH\x00\x42\t\n\x07\x63ontext\"\'\n\x04Hash\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\thash_type\x18\x02 \x01(\t\"Z\n\rSearchRequest\x12\r\n\x03url\x18\x01 \x01(\tH\x00\x12\x15\n\x04hash\x18\x02 \x01(\x0b\x32\x05.HashH\x00\x12\x19\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x08.ContextB\x08\n\x06search\"L\n\x0bScanRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x15\n\rartifact_type\x18\x02 \x01(\t\x12\x19\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x08.Context\"1\n\x06Result\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x19\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x08.Contextb\x06proto3'
)




_TELEGRAMCONTEXT = _descriptor.Descriptor(
  name='TelegramContext',
  full_name='TelegramContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_id', full_name='TelegramContext.chat_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='TelegramContext.message_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='TelegramContext.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=88,
)


_TWITTERCONTEXT = _descriptor.Descriptor(
  name='TwitterContext',
  full_name='TwitterContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=106,
)


_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telegram', full_name='Context.telegram', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twitter', full_name='Context.twitter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context', full_name='Context.context',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=108,
  serialized_end=202,
)


_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='Hash.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_type', full_name='Hash.hash_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=243,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='SearchRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='SearchRequest.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='SearchRequest.context', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='search', full_name='SearchRequest.search',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=245,
  serialized_end=335,
)


_SCANREQUEST = _descriptor.Descriptor(
  name='ScanRequest',
  full_name='ScanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='ScanRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artifact_type', full_name='ScanRequest.artifact_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='ScanRequest.context', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=413,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Result.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='Result.context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=464,
)

_CONTEXT.fields_by_name['telegram'].message_type = _TELEGRAMCONTEXT
_CONTEXT.fields_by_name['twitter'].message_type = _TWITTERCONTEXT
_CONTEXT.oneofs_by_name['context'].fields.append(
  _CONTEXT.fields_by_name['telegram'])
_CONTEXT.fields_by_name['telegram'].containing_oneof = _CONTEXT.oneofs_by_name['context']
_CONTEXT.oneofs_by_name['context'].fields.append(
  _CONTEXT.fields_by_name['twitter'])
_CONTEXT.fields_by_name['twitter'].containing_oneof = _CONTEXT.oneofs_by_name['context']
_SEARCHREQUEST.fields_by_name['hash'].message_type = _HASH
_SEARCHREQUEST.fields_by_name['context'].message_type = _CONTEXT
_SEARCHREQUEST.oneofs_by_name['search'].fields.append(
  _SEARCHREQUEST.fields_by_name['url'])
_SEARCHREQUEST.fields_by_name['url'].containing_oneof = _SEARCHREQUEST.oneofs_by_name['search']
_SEARCHREQUEST.oneofs_by_name['search'].fields.append(
  _SEARCHREQUEST.fields_by_name['hash'])
_SEARCHREQUEST.fields_by_name['hash'].containing_oneof = _SEARCHREQUEST.oneofs_by_name['search']
_SCANREQUEST.fields_by_name['context'].message_type = _CONTEXT
_RESULT.fields_by_name['context'].message_type = _CONTEXT
DESCRIPTOR.message_types_by_name['TelegramContext'] = _TELEGRAMCONTEXT
DESCRIPTOR.message_types_by_name['TwitterContext'] = _TWITTERCONTEXT
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['ScanRequest'] = _SCANREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelegramContext = _reflection.GeneratedProtocolMessageType('TelegramContext', (_message.Message,), {
  'DESCRIPTOR' : _TELEGRAMCONTEXT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:TelegramContext)
  })
_sym_db.RegisterMessage(TelegramContext)

TwitterContext = _reflection.GeneratedProtocolMessageType('TwitterContext', (_message.Message,), {
  'DESCRIPTOR' : _TWITTERCONTEXT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:TwitterContext)
  })
_sym_db.RegisterMessage(TwitterContext)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:Context)
  })
_sym_db.RegisterMessage(Context)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), {
  'DESCRIPTOR' : _HASH,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:Hash)
  })
_sym_db.RegisterMessage(Hash)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

ScanRequest = _reflection.GeneratedProtocolMessageType('ScanRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCANREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:ScanRequest)
  })
_sym_db.RegisterMessage(ScanRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
